In [1]:
import numpy as np

In [2]:
arr_0 = np.array(5) # 0 dimentional array
print(arr_0)
print("Number of dimensions:", arr_0.ndim)

5
Number of dimensions: 0


In [3]:
arr_1 = np.array([1,2,3]) # 1 dimentional array
print(arr_1)
print("Number of dimensions:", arr_1.ndim)

[1 2 3]
Number of dimensions: 1


In [4]:
arr_2 = np.array([[1,2,3],[4,5,6]]) # 2 dimentional array
print(arr_2)
print("Number of dimensions:", arr_2.ndim)
print("Shape of array:", arr_2.shape)
print("Size of array:", arr_2.size)
print("Data type of array elements:", arr_2.dtype)
print("Transfor Array:", arr_2.T)

[[1 2 3]
 [4 5 6]]
Number of dimensions: 2
Shape of array: (2, 3)
Size of array: 6
Data type of array elements: int64
Transfor Array: [[1 4]
 [2 5]
 [3 6]]


In [5]:
arr = np.array([1, 2, 3, 4, 5], dtype='float64')
arr

array([1., 2., 3., 4., 5.])

In [6]:
arr_copy = np.copy(arr)
arr_copy

array([1., 2., 3., 4., 5.])

In [7]:
# create a numpy array with 0
arr_zeros = np.zeros((3,4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# creating a numpy array with 1
arr_ones = np.ones((6,7))
arr_ones

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [9]:
# create a numpy array with empty values
arr_empty = np.empty((2,3))
arr_empty

array([[1.e-323, 0.e+000, 0.e+000],
       [0.e+000, 0.e+000, 0.e+000]])

In [10]:
arr_full = np.full((2,3), 7)
arr_full

array([[7, 7, 7],
       [7, 7, 7]])

In [11]:
# imitate the shape and type of an existing array
arr_like = np.zeros_like(arr_2)
arr_like

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
# squence of numbers
arr_seq = np.arange(10, 21, 2)
arr_seq

array([10, 12, 14, 16, 18, 20])

In [13]:
arr_lin = np.linspace(0, 5, 5)
arr_lin

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [14]:
arr_log = np.logspace(1, 3, 3)
arr_log

array([  10.,  100., 1000.])

In [15]:
# identity matrix
arr_identity = np.eye(4,dtype=int)
arr_identity

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [16]:
# diagonal matrix
arr_diag = np.diag([1,2,3,4])
arr_diag

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [17]:
# random array (distribution between 0 and 1)
arr_rand = np.random.rand(3,4)
arr_rand

array([[0.49006209, 0.74261591, 0.98085194, 0.27386982],
       [0.58722433, 0.26072951, 0.57575665, 0.82832594],
       [0.43480807, 0.13606705, 0.27388812, 0.28194983]])

In [18]:
# rnandom array selected range
arr_rand_range = np.random.uniform(10, 20, (2,3))
print(arr_rand_range)

arr_rand_int = np.random.randint(1, 10, (2,3))
print(arr_rand_int)

[[14.11163081 11.23692184 19.70830889]
 [16.29591408 15.34215981 12.09914251]]
[[6 4 2]
 [1 1 9]]


In [19]:
# normal distribution
arr_normal = np.random.randn(3,4)
arr_normal

array([[-0.126327  , -0.37281073,  0.69918759,  0.42814082],
       [ 0.72347383,  1.02288711,  0.77814406,  1.41991851],
       [-1.64232431,  0.02144268, -0.44354116,  1.09362429]])

In [20]:
# set the random seed
np.random.seed(42)
arr_seed = np.random.randint(1, 10, (2,3))
arr_seed

array([[7, 4, 8],
       [5, 7, 3]], dtype=int32)

Data Type

bool

int: int8, int16, int32, int64

uint: uint8, uint16, uint32, uint64

float: float16, float32, float64

complex: complex64, complex128

In [21]:
arr_slice_1 = np.random.randint(1, 100, 10)
print(arr_slice_1)
print("Sliced array:", arr_slice_1[::-1])
print("boolean indexing:", arr_slice_1[(arr_slice_1 % 2 == 0) & (arr_slice_1 > 50)])
print("sliced array:", arr_slice_1[slice(2,8,2)])

[87 75 75 88 24  3 22 53  2 88]
Sliced array: [88  2 53 22  3 24 88 75 75 87]
boolean indexing: [88 88]
sliced array: [75 24 22]


In [22]:
arr_slice_2D = np.random.randint(1, 100, (4,5))
print(arr_slice_2D)
print("Sliced one number from 2D array:", arr_slice_2D[2,3])
print("Sliced 2D array:", arr_slice_2D[1:3, 2:5])
print("Sliced all rows for specific column:", arr_slice_2D[:,2])
print("conditional indexing:", arr_slice_2D[:,2][arr_slice_2D[:,2] % 2 == 0])

[[30 38  2 64 60]
 [21 33 76 58 22]
 [89 49 91 59 42]
 [92 60 80 15 62]]
Sliced one number from 2D array: 59
Sliced 2D array: [[76 58 22]
 [91 59 42]]
Sliced all rows for specific column: [ 2 76 91 80]
conditional indexing: [ 2 76 80]


In [23]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
array_sum = np.add(array_1, array_2)
print("Sum:", array_sum)
array_diff = np.subtract(array_2, array_1)
print("Difference:", array_diff)
array_mul = np.multiply(array_1, array_2)
print("Multiplication:", array_mul)
array_div = np.divide(array_2, array_1)
print("Division:", array_div)

Sum: [5 7 9]
Difference: [3 3 3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]


In [24]:
array_3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_4 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print(array_3 + array_4)
print(array_3 - array_4)
print(array_3 * array_4)
print(array_3 / array_4)

print(array_3 @ array_4)  # Matrix multiplication

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [25]:
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])
print(a + b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [26]:
# square root
arr_sqrt = np.sqrt(np.array([1,4,9,16,25]))
print(arr_sqrt)
# exponential
arr_exp = np.exp(np.array([1,2,3,4,5]))
print(arr_exp)
# logarithm
arr_log = np.log(np.array([1,10,100,1000,10000]))
print(arr_log)
# absolute value
arr_abs = np.abs(np.array([-1, -2, 3, -4, 5]))
print(arr_abs)
# power
arr_power = np.power(np.array([1,2,3,4,5]), 2)
print(arr_power)
# round
arr_round = np.round(np.array([1.7, 2.5, 3.9, 4.1, 5.6]))
print(arr_round)
# ceiling
arr_ceil = np.ceil(np.array([1.2, 2.5, 3.1, 4.7, 5.3]))
print(arr_ceil)
# floor
arr_floor = np.floor(np.array([1.8, 2.3, 3.6, 4.9, 5.1]))
print(arr_floor)

# Nan
np.isnan(np.array([1, 2, np.nan, 4, np.nan]))

[1. 2. 3. 4. 5.]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         2.30258509 4.60517019 6.90775528 9.21034037]
[1 2 3 4 5]
[ 1  4  9 16 25]
[2. 2. 4. 4. 6.]
[2. 3. 4. 5. 6.]
[1. 2. 3. 4. 5.]


array([False, False,  True, False,  True])

In [27]:
array = np.array([1,3,5,2,8,9,9,4,6,7])

print('Sum',np.sum(array))
print('Mean',np.mean(array))
print('Median',np.median(array))
print('Std',np.std(array))
print('Var',np.var(array))

print(np.max(array),np.argmax(array))
print(np.min(array),np.argmin(array))


print('25th Percentile',np.percentile(array, 25))

print('Cumulative Sum',np.cumsum(array))

Sum 54
Mean 5.4
Median 5.5
Std 2.727636339397171
Var 7.4399999999999995
9 5
1 0
25th Percentile 3.25
Cumulative Sum [ 1  4  9 11 19 28 37 41 47 54]


In [28]:
print(np.greater(array, 4))
print(np.less(array, 4))
print(np.equal(array, 5))

print(np.logical_and(array > 2, array < 8))
print(np.logical_or(array < 2, array > 8))

print(np.any(array > 8))
print(np.all(array > 0))

print(np.where(array % 2 == 0, array, 0))

[False False  True False  True  True  True False  True  True]
[ True  True False  True False False False False False False]
[False False  True False False False False False False False]
[False  True  True False False False False  True  True  True]
[ True False False False False  True  True False False False]
True
True
[0 0 0 2 8 0 0 4 6 0]


In [29]:
print(np.sort(array))
print(np.argsort(array))

print(np.unique(array))

[1 2 3 4 5 6 7 8 9 9]
[0 3 1 7 2 8 9 4 6 5]
[1 2 3 4 5 6 7 8 9]


In [30]:
print(np.reshape(array, (2,5)))

[[1 3 5 2 8]
 [9 9 4 6 7]]
